language: node_js

# blocklist
# branches:
# except:
#   - "_F-TypeScript"

node_js:
  - "lts/*"
  - "stable"

git:
  clone: false # If you use this option, the TRAVIS_COMMIT_MESSAGE environment variable will not be defined

cache: npm

before_install:
  - npm i -g makeshift && makeshift -r registry.npmjs.org
  - git clone "https://$CI_USER_NAME:$CI_USER_TOKEN@github.com/$TRAVIS_REPO_SLUG.git" $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git config user.email "$CI_USER_EMAIL"
  - git config user.name "$CI_USER_NAME"
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git checkout -f $TRAVIS_BRANCH --

script:
  - npm run test

jobs:
  include:
    # ===========================================
    # Nightly merge from master to dev
    # ===========================================
    - stage: nightly-merge-master-to-dev
      name: "Merge code from master to dev on a nightly basis if there are no conflicts"
      node_js: "stable"
      if: type = cron AND branch = master
      before_script:
        - chmod +x scripts/daily-branch-merge.sh
        - git update-index --assume-unchanged scripts/daily-branch-merge.sh
      script:
        - npm run test # Runs test first before attempting merge
        - scripts/daily-branch-merge.sh $TRAVIS_BRANCH
      after_script:
        - git update-index --no-assume-unchanged scripts/daily-branch-merge.sh
    # ================================================================
    # Deployment stage that only runs on a stable version of node
    # ================================================================
    - stage: deploy
      name: "Publish a new distribution to NPM"
      node_js: "stable"
      if: fork = false AND type = push # Publish only on push events on branches in the org
      script: skip # Tests would have already been run before this
      before_deploy:
        - chmod +x scripts/semver.sh
        - chmod +x scripts/bump-version.sh
        - chmod +x scripts/version-deprecator.sh
        - chmod +x scripts/publish-typedoc.sh
        - git update-index --assume-unchanged scripts/bump-version.sh
        - git update-index --assume-unchanged scripts/semver.sh
        - git update-index --assume-unchanged scripts/version-deprecator.sh
        - git update-index --assume-unchanged scripts/publish-typedoc.sh
      deploy:
        - provider: script
          script: scripts/bump-version.sh $TRAVIS_BRANCH
          skip_cleanup: true
          on:
            all_branches: true
            repo: romcal/romcal
        - provider: script
          script: scripts/version-deprecator.sh $TRAVIS_BRANCH
          skip_cleanup: true
          on:
            branch: master
            repo: romcal/romcal
        - provider: script
          script: scripts/publish-typedoc.sh $TRAVIS_BRANCH
          skip_cleanup: true
          on:
            all_branches: true
            repo: romcal/romcal
      after_deploy:
        - git update-index --no-assume-unchanged scripts/bump-version.sh
        - git update-index --no-assume-unchanged scripts/semver.sh
        - git update-index --no-assume-unchanged scripts/version-deprecator.sh
        - git update-index --no-assume-unchanged scripts/publish-typedoc.sh
notifications:
  email:
    recipients:
      - $CI_USER_EMAIL
    on_success: change
    on_failure: always
